# Generated by Django 5.2.7 on 2025-10-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_alter_category_options_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
